version: '3.8'

services:
  skillscope:
    build: .
    container_name: skillscope
    ports:
      - "8501:8501"  # Main app
      - "8502:8502"  # Admin app
    volumes:
      - ./data:/app/data  # Persist the data directory
    environment:
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
